# Generated by Django 4.2.1 on 2023-06-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntialParameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year_start', models.DateField(default='2019-1-1')),
                ('fiscal_year_end', models.DateField(default='2019-12-31')),
                ('starting_balance', models.FloatField(default=40000.0)),
                ('monthly_reserve_contribution', models.FloatField(default=55.55555555555556)),
                ('current_yearly_reserve_contribution', models.FloatField(default=20000.0)),
                ('proposed_yearly_reserve_contribution', models.FloatField(default=1.0)),
                ('inflation', models.FloatField(default=3.0)),
                ('Number_of_units', models.IntegerField(default=1)),
                ('Default_interest_rate', models.FloatField(default=0.0)),
                ('Total_assessment_amount_per_month', models.FloatField(default=1.0)),
                ('minus_delinquent_payments', models.BooleanField(default=False)),
                ('delinquent_discount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=100)),
                ('last_saved_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('MonthalyCommonExpenses', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('last_saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_saved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsIfVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(default='', max_length=100)),
                ('building', models.IntegerField(default=1)),
                ('address', models.CharField(default='New address', max_length=100)),
                ('square_footage', models.FloatField(default=100.0, max_length=100)),
                ('percentage', models.FloatField(default=100.0)),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAssessments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default=-1)),
                ('amount', models.FloatField(default=0.0)),
                ('purpose', models.CharField(blank=True, default='None', max_length=100)),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement')),
            ],
        ),
        migrations.CreateModel(
            name='MonthalyCommonExpenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='other', max_length=100)),
                ('Component_title', models.CharField(blank=True, default='New Component', max_length=100)),
                ('description', models.CharField(blank=True, default='New', max_length=100)),
                ('monthly_replacement_cost', models.FloatField(default=1.0)),
                ('Notes', models.CharField(blank=True, default='None', max_length=100)),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoanOtherExpenditures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default=-1)),
                ('Amount_due', models.FloatField(default=0.0)),
                ('Description', models.CharField(default='There are no other expenditures')),
                ('fund_component', models.CharField(default='Not funded')),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement')),
                ('year_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.intialparameters')),
            ],
        ),
        migrations.AddField(
            model_name='intialparameters',
            name='scenario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement'),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='other', max_length=100)),
                ('Component_title', models.CharField(blank=True, default='New Component', max_length=100)),
                ('description', models.CharField(blank=True, default='New', max_length=100)),
                ('useful_life_year', models.IntegerField(default=0)),
                ('remaining_useful_life_years', models.IntegerField(default=0)),
                ('current_replacement_cost', models.FloatField(default=1.0)),
                ('assessement', models.CharField(blank=True, default='Fixed', max_length=100)),
                ('Fund_component', models.CharField(blank=True, default='Funded', max_length=100)),
                ('Notes', models.CharField(blank=True, default='None', max_length=100)),
                ('scenario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_management.scenariomanagement')),
            ],
        ),
    ]
