# Generated by Django 4.2.1 on 2023-06-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomanagement',
            name='last_saved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
