# Generated by Django 4.2.1 on 2023-06-21 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario_management', '0002_alter_scenariomanagement_last_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariomanagement',
            name='created_by',
        ),
        migrations.AddField(
            model_name='scenariomanagement',
            name='read_access_users',
            field=models.ManyToManyField(blank=True, related_name='scenarios_with_read_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenariomanagement',
            name='write_access_users',
            field=models.ManyToManyField(blank=True, related_name='scenarios_with_write_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
