# Generated by Django 4.2.1 on 2023-06-19 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('company', models.CharField(blank=True, max_length=225, null=True)),
                ('position', models.CharField(blank=True, max_length=225, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=225, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(blank=True, default='demo_community', max_length=100)),
                ('community_address', models.CharField(blank=True, default='demo', max_length=100)),
                ('subscription_type', models.CharField(blank=True, default='Standard', max_length=100)),
                ('period', models.CharField(default='2023-2024')),
                ('max_number_of_scenarios', models.IntegerField(default=5)),
                ('subscription_status', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
